Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
empty_array = np.empty((2, 2));
print(empty_array)

[[4.79204955e-310 0.00000000e+000]
 [6.59684619e-310 6.59684614e-310]]


In [ ]:
import numpy as np
all_one_array = np.ones((4, 2));
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
new_array = np.full((2, 2), 5);
print(new_array)

[[5 5]
 [5 5]]


In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4]);
new_array = np.zeros_like(array);
print(new_array)

[0 0 0 0]


In [ ]:
import numpy as np
array = np.array([1, 2, 3, 4]);
new_array = np.ones_like(array);
print(new_array)

[1 1 1 1]


In [ ]:
import numpy as np
list = [1, 2, 3, 4];
array = np.array(list);
print(array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
array = np.arange(10, 50);
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np
array = np.arange(0, 9).reshape(3, 3);
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
array = np.eye(3);
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array = np.random.random(30);
mean = array.mean();
print(mean)

0.508715680722758


In [ ]:
import numpy as np
array = np.random.random((10, 10));
min_value = array.min();
max_value = array.max();
print(min_value, max_value)

In [ ]:
import numpy as np
array = np.zeros(10);
array[4] = 1;
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0]);
non_zero_indices = np.nonzero(arr);
reversed_arr = arr[non_zero_indices[::-1]]
print(reversed_arr)

[1 2 4]


In [ ]:
import numpy as np
array = np.ones((5, 5));
array[1:-1, 1:-1] = 0;
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
array = np.zeros((8, 8));
array[1::2, ::2] = 1;
array[::2, 1::2] = 1;
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
add = np.add(x, y);
v = np.array([9,10]);
w = np.array([11,12]);
add1 = np.add(v, w);
print(add)
print(add1)

[[ 6  8]
 [10 13]]
[20 22]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
subtract = np.subtract(x, y);
v = np.array([9,10]);
w = np.array([11,12]);
subtract1 = np.subtract(v, w);
print(subtract)
print(subtract1)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
multiply = np.multiply((x, y), 5);
v = np.array([9,10]);
w = np.array([11,12]);
multiply1 = np.multiply((v, w), 6);
print(multiply)
print(multiply1)

[[[ 5 10]
  [15 25]]

 [[25 30]
  [35 40]]]
[[54 60]
 [66 72]]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
square = np.square(x);
square1 = np.square(y);
v = np.array([9,10]);
w = np.array([11,12]);
square2 = np.square(v);
square3 = np.square(w);
print(square)
print(square1)
print(square2)
print(square3)

[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
dot_product = np.dot(x, y);
v = np.array([9,10]);
w = np.array([11,12]);
dot_product1 = np.dot(v, w);
x = np.array([[1, 2], [3, 5]]);
v = np.array([9,10]);
dot_product2 = np.dot(x, v);
print(dot_product)
print(dot_product1)
print(dot_product2)

[[19 22]
 [50 58]]
219
[29 77]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
y = np.array([[5, 6], [7, 8]]);
concatenate = np.concatenate((x, y), axis=1);
v = np.array([9,10]);
w = np.array([11,12]);
concatenate1 = np.concatenate((v, w), axis = 0);
print(concatenate)
print(concatenate1)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 5]]);
v = np.array([9,10]);
concatenate = np.concatenate(x, v);
print(concatenate)
#

TypeError: only integer scalar arrays can be converted to a scalar index

The error occurs because here the np.concatenate function requires matching dimensions but in the given question, x is a 2D array and v is a 1D array.

Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ≠ BA.
3. Prove (AB)
T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]]);
B = np.array([[5, 3], [2, 1]]);

A_inverse = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inverse)
print("A * A^(-1):\n", identity_matrix)

A * A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]]);
B = np.array([[5, 3], [2, 1]]);
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]]);
B = np.array([[5, 3], [2, 1]]);
AB = np.dot(A, B)
ABT = np.transpose(AB)
AT = np.transpose(A)
BT = np.transpose(B)
BTAT = np.dot(BT, AT)
print("(AB)^T:\n", ABT)
print("(B)^T(A)^T:\n", BTAT)

(AB)^T:
 [[23 51]
 [13 29]]
(B)^T(A)^T:
 [[23 51]
 [13 29]]


In [ ]:
import numpy as np
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])
A_inverse = np.linalg.inv(A)
x = np.dot(A_inverse, B)
print("Solution:\n", x)

Solution:
 [ 2.  1. -2.]
